# CI on Windows via appveyor
# This file was based on Olivier Grisel's python-appveyor-demo

environment:

  global:
      PYTHON: "C:\\conda"
      PYTHON_ARCH: "64"

  matrix:
    - PYTHON_VERSION: "3.7"
      CONDA_DEPENDENCIES: "numpy scipy pandas scikit-learn scikit-learn matplotlib seaborn tqdm openpyxl numba pyqt cython"
      PIP_DEPENDENCIES: "pyqtgraph neo"

platform:
    -x64

install:
  # Install conda using ci-helpers. More information about ci-helpers can
  # be found here: https://github.com/astropy/ci-helpers
  - "git clone git://github.com/astropy/ci-helpers.git"
  - "rm ci-helpers/test_env.py"
  - "powershell ci-helpers/appveyor/install-miniconda.ps1"

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Switch to test environment
  - "activate test"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct, sys; print(struct.calcsize('P') * 8); print(sys.executable)\""
  
  # install hdbscan form conda forge
  - "conda install -y -c conda-forge hdbscan"

  # Install tridesclous
  - "python setup.py develop"
  - "python -c \"import tridesclous; print(tridesclous.__version__)\""

build: false

test_script:
  - 'netsh advfirewall firewall add rule name="tridesclous" dir=in action=allow program="C:\Python34-conda64\python.exe" enable=yes'
  - "py.test -sv tridesclous/tests"
