# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.8
jobs:
  test-3.8:
    docker:
      - image: circleci/python:3.8.7-buster

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v4-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v4-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r .circleci/requirements_testing.txt
            pip install -r requirements.txt



      - save_cache:
          paths:
            - ./venv
          key: v4-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: install tridesclous
          command: |
            . venv/bin/activate
            python setup.py install

      # run tests!
      # only core is tested at the moment (tridesclous/tests) not the online
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest tridesclous/tests

      - store_artifacts:
          path: test-reports
          destination: test-reports

